---
- name: Install the selinux python module
  yum: name=libselinux-python state=present
  become: true
  when: ansible_os_family == "RedHat"
  tags: [packages,nginx]

- name: Copy the epel packages
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel_ansible.repo
  become: true
  when: nginx_is_el | bool
  tags: [packages,nginx]

- name: Install the nginx packages
  yum: name={{ item }} state=present disablerepo='*' enablerepo={{ yum_epel_repo }},{{ yum_base_repo }}
  become: true
  with_items: "{{ nginx_redhat_pkg }}"
  when:  nginx_is_el | bool
  tags: [packages,nginx]

- name: Install the nginx packages
  yum: name={{ item }} state=present
  become: true
  with_items: "{{ nginx_redhat_pkg }}"
  when: ansible_os_family == "RedHat" and not {{ nginx_is_el }} | bool
  tags: [packages,nginx]

- name: Install the nginx packages
  apt: name={{ item }} state=present update_cache=yes
  become: true
  with_items: "{{ nginx_ubuntu_pkg }}"
  environment: "{{ env }}"
  when: ansible_os_family == "Debian"
  tags: [packages,nginx]

# Save home directory to "home" envvar
- shell: echo ~
  register: nginx_home
  when: "{{ nginx_letsencrypt }}"

- name: Ensure ~/bin exists
  file: path={{nginx_home.stdout}}/bin state=directory
  when: "{{ nginx_letsencrypt }}"

- name: Download certbot-auto
  get_url: url=https://dl.eff.org/certbot-auto dest={{nginx_home.stdout}}/bin/certbot-auto mode=0755
  when: "{{ nginx_letsencrypt }}"
